### ISSUE TITLE
What HA version use ?

### ISSUE THREAD

**Issue by MiGaNuTs** [KVSoong/asyncua#2]
Hi,

I'm trying to use your component in my HA setup. I get this message at startup.

Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend_experimental", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 49: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

what version of HA can I use for your component to work?
Is there an updated version or another fork to read values ​​from an OPC-UA PLC?

Thanks.

**Comment by KVSoong** [comment]
Hi MiGuNuts,

last I checked, it is running with 2024.06 without any issue. I have not update my homeassistant to 2024.07. Are you able to test this integration with 2024.06 on your machine? But judging from the logs message, it seems to be related to hacs integration.

**Comment by MiGaNuTs** [comment]
I use the latest version of HA. The problems seems to be in my PLC configuration. I made some changes on it, and now it works.
my plc doesn't like share variables by id/numbers. if i share variables by strings/names, it works.
